name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name : Reporting
        run:
          echo 'My first CML report' > report.md
          cml-publish plot.png --md > report.md
          cml-send-comment report.md
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
