name: Python Package
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - run: |
          # train will generate plot.png
          python train.py

          echo 'My first CML report' > report.md
          cml-publish plot.png --md > report.md
          cml-send-comment report.md